[project]
name = "dz-catalog-analysis-bocharov-m26-555"
version = "0.1.0"
description = "Homework 1: streaming catalog analysis"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[dependency-groups]
dev = [
    "ruff==0.12.1",
]
